# Generated by Django 3.2.12 on 2023-07-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': 'Подтверждение почты', 'verbose_name_plural': 'Подтверждения почты'},
        ),
    ]
